### ISSUE TITLE
Need more customization for the login screen

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-workflows#15]
#### Describe the desired behavior
Some users need a greater amount of flexibility on the login screen. For example:
- hiding/disabling the Remember Me functionality
- hiding/disabling the registration elements
- adding additional custom links (Terms and Conditions, Privacy Policy) / content

#### Describe the current behavior
These items are not customizable

#### Is this request related to a current issue?
This is a requirement that is needed for the Green Seed UI to be able to use our workflow.

**Comment by jeffvg** [comment]
moved to PXBLUE-1923
