### ISSUE TITLE
Customize Account Details

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-workflows#3]
#### Describe the desired behavior
End users should be able to specify what details they want to capture on the account details screen of registration. The should be able to specify which fields are required, custom validation for fields, etc.

#### Describe the current behavior
Only three hardcoded fields (first, last, phone).

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
This will likely be part of the updates we make to the RNAW project as part of our realignment with the shiverware implementation.

It would be nice to have on the React side too, but not as critical since there isn't another implementation that already has this feature.

**Comment by jeffvg** [comment]
moved to PXBLUE-1927
