### ISSUE TITLE
Support Logging in with Username or Email

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-workflows#48]
#### Describe the desired behavior
Users should be able to configure the auth workflow login to work with username or email.

#### Describe the current behavior
Only email address is supported.

#### Is this request related to a current issue?
This is a request from the Red/Green seed teams.

#### Additional Context
Should we also support the ability to customize the email regex?

**Comment by huayunh** [comment]
Not related but does the White team support user name without email?

**Comment by joebochill** [comment]
> Not related but does the White team support user name without email?

Kind of related. They don’t as far as I know, but red/green seed apps are not connected to PX White. And our login workflow is technically independent of any particular back-end, so I think it makes sense to support usernames to be even more flexible.
