### ISSUE TITLE
Back button is disabled

### ISSUE THREAD

**Issue by daileytj** [pxblue/react-workflows#51]
#### Describe the bug
The back button is disabled at various points in the self-register and invite-register workflows

#### What is the expected behavior?
The back button should not be disabled

#### What are the steps to reproduce?
Self Register Workflow
1. Run login workflow
2. Click on the "create account" link to start workflow
3. Continue through the workflow and notice that the back button for the "verify email" and "create password" pages is disabled.

Invite Register Workflow
1. Run login workflow
2. Click the debug button
3. Click "test invite register" link
4. notice that the back button for the "license agreement" page is disabled.

#### Screenshots or links to minimum reproduction example
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-28 at 10 28 24](https://user-images.githubusercontent.com/13989985/119999511-d3db4500-bf9f-11eb-8dce-15f97f833758.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-28 at 10 28 32](https://user-images.githubusercontent.com/13989985/119999513-d473db80-bf9f-11eb-967d-dca607e584f6.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-28 at 10 28 54](https://user-images.githubusercontent.com/13989985/119999551-ddfd4380-bf9f-11eb-8b2c-b1947b2e8419.png)

**Comment by joebochill** [comment]
This might've been on purpose because of how the PX White workflow wrks...i'd have to think about it

**Comment by huayunh** [comment]
Make the button state customizable — right now it is not determined by the user

**Comment by huayunh** [comment]
Mentioned as part of PXBLUE-2139
