### ISSUE TITLE
Change the order of the EULA screen

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-workflows#6]
#### Describe the desired behavior
I think the email address page and the email verification code page should be back to back.

So either EULA -> Enter Email -> Enter Code, or Enter Email -> Enter Code -> EULA
But not EULA in the middle

_Originally posted by @huayunh in https://github.com/pxblue/react-workflows/pull/2#issuecomment-682127224_
#### Describe the current behavior
Eula appears after entering the email address but before verifying the email address.

#### Is this request related to a current issue?
No

#### Additional Context
We will need to work with PX White to understand the technical reasons for why the screens are currently presented in this order.

**Comment by huayunh** [comment]
I'm working on the login patterns, and it looks like we have all the screens doing EULA following the enter email screen.

**Comment by joebochill** [comment]
The implementation of the registration screens right now is in line with the PX White R11 implementation. If we want to change the order of the screens, we will need to discuss with them about plans to change how they do user registration.

**Comment by jeffvg** [comment]
moved to PXBLUE-1925
