### ISSUE TITLE
Better multi-language support

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-workflows#7]
#### Describe the desired behavior
The workflow should support multiple languages. It should use the browser default language by default but there should also be instructions for how to change the language if desired.

#### Describe the current behavior
The current default is set to english and there are no instructions for how to change the language.

#### Additional Context
The PX Green team has created this exact behavior in the Seed UI, so we may be able to get in touch with them to see how they did this.

**Comment by joebochill** [comment]
We can leave this where it is for now until we start seeing higher adoption of the workflow.

**Comment by jeffvg** [comment]
moved to PXBLUE-1924
