### ISSUE TITLE
Change Password Modal Does Not Display Error Message

### ISSUE THREAD

**Issue by misskaseyann** [pxblue/react-workflows#77]
#### Describe the bug
When the AccountUIActions `changePassword` function throws on error, the message in that error does not get displayed.

In the `ChangePasswordModal.tsx` on line 86:
`setTransitState(transitFailed(error.errorMessage));`
should actually be:
`setTransitState(transitFailed(error.message));`

#### What is the expected behavior?
The thrown error in the AccountUIActions `changePassword` should have its message displayed in the modal.

#### What are the steps to reproduce?
1. Ensure that the `changePassword` function in AccountUIActions throws: `new Error('Something bad happened');`
2. Cause a failure on the Change Password modal.
3. See that the error dialog is empty.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/20075449/127881601-016739ef-dda2-4468-a320-b6a4fd8ccfa8.png)

#### Anything else to add?
I am assuming that the pattern for all AccountUIActions are the same (return on success, throw on error). If this function is intended to be different, it would be good to update the documentation given.

**Comment by joebochill** [comment]
This is a great catch @misskaseyann. These functions should be the same between react and react native. We will get a fix in for this shortly. Thanks for pointing us right to the culprit!

https://github.com/pxblue/react-workflows/pull/80

**Comment by joebochill** [comment]
The fix for this should now be available in version 2.3.1.
